### ISSUE TITLE
Error when installing with bash version 5

### ISSUE THREAD

**Issue by reyrodrigez** [ohmybash/oh-my-bash#125]
The error below shown when I tried to install `oh-my-bash` on top of bash version 5:
```
Error: Bash 4 required for Oh My Bash.
Error: Upgrade Bash and try again.
```

I've just installed bash latest which is `5.0.11`:

```
$ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
```

~I'm going to downgrade my bash to 4 for now.~
Didn't get the error when cloning the repo and running `$ ./tools/install.sh`. Only seems to be an issue when running the `curl` or `wget` from githubusercontent.com

**Comment by k001** [comment]
That's because `sh` points to `Bash` points to the older version, so try install using `Bash` instead of `sh`.
You can validate with this command:
`sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.`

Use this command instead:
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"`

**Comment by Chaunce-y** [comment]
I had the same issue as reyrodrigez above. using k001's suggestion to use the command to install oh-my-bash using bash shell worked for me, thank you.

**Comment by k001** [comment]
Based on #167 this issue it already documented, so maybe we can close this.

**Comment by reyrodrigez** [comment]
Closing, thanks all
