### ISSUE TITLE
theme disappears when switched to root user

### ISSUE THREAD

**Issue by rpotter12** [ohmybash/oh-my-bash#140]
OS: Ubuntu 19.10

When we switch to root user by `sudo su`, the theme disappears. 

## How to solve this: 
 edit `/root/.bashrc` file to apply the theme to root user also.

**Comment by nntoan** [comment]
Hi @rpotter12,

That's the expected behaviour and not an issue. OhMyBash or any other similar framework should be installed for the current user only.

If you want to use OhMyBash for a different user, just simply switch to that user and install it.

Feel free to reopen if you have further question.

**Comment by alinpr18** [comment]
You can use a symbolic link

`ln -s -f /home/user/.bashrc /root/.bashrc`
