### ISSUE TITLE
sh: 33: [: Illegal number:

### ISSUE THREAD

**Issue by MacroBull** [ohmybash/oh-my-bash#213]
From the installation command from the homepage:
> sh -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)"

Are you seriously sure this install script works for dash?

**Comment by locobastos** [comment]
Could you please run this command and share the sdtout ?

`sh -x -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)"`

**Comment by akinomyoga** [comment]
I think the error message is caused by `[ "$ncolors" -gt 8 ]` where `$ncolors` is an empty string.

```bash
$ dash -c '[ "" -gt 8 ]'
dash: 1: [: Illegal number:
```

Even if there is a command `tput`, it doesn't necessarily support the terminfo names but maybe only supports the termcap names.  We should care about different `tput` implementations. Some implementations such as `tput` in GNU/Linux (ncurses) only support terminfo names. Some other implementations such as FreeBSD `tput` only support the termcap names. Some other implementations support both names (though there are a few name conflicts).

@MacroBull, you should provide the information of which operating system you are using.

To support different `tput` implementation, one way is to try both names of terminfo/termcap. If both fail, one should assign a fallback value (e.g. -1 as for `TERM=dumb`).

```bash
ncolors=$(tput colors 2>/dev/null || tput Co 2>/dev/null || echo -1)
```

**Comment by MacroBull** [comment]
> Could you please run this command and share the sdtout ?
> 
> `sh -x -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)"`

```shell
~$ sh -x -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)"
+ main
+ which tput
+ tput colors
+ ncolors=256
+ [ -t 1 ]
+ [ -n 256 ]
+ [ 256 -ge 8 ]
+ tput setaf 1
+ RED=
+ tput setaf 2
+ GREEN=
+ tput setaf 3
+ YELLOW=
+ tput setaf 4
+ BLUE=
+ tput bold
+ BOLD=
+ tput sgr0
+ NORMAL=
+ set -e
+ [ -n ]
+ echo
+ cut -d . -f 1
+ bash_major_version=
+ [  -lt 4 ]
sh: 33: [: Illegal number:
+ [ ! -n  ]
+ OSH=/home/caros/.oh-my-bash
+ [ -d /home/caros/.oh-my-bash ]
+ umask g-w,o-w
+ printf Cloning Oh My Bash...\n
Cloning Oh My Bash...
+ hash git
+ [  = cygwin ]
+ env git clone --depth=1 https://github.com/ohmybash/oh-my-bash.git /home/caros/.oh-my-bash
Cloning into '/home/caros/.oh-my-bash'...
```

**Comment by akinomyoga** [comment]
There are several issues with the current install script, so I made a PR at #214.

> From the installation command from the homepage:
>
> ```
> sh -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)"
> ```

Also, the web page of the oh-my-bash at https://ohmybash.nntoan.com/ needs to be updated.  [`README`](https://github.com/ohmybash/oh-my-bash/blob/master/README.md) in the repository has already been updated on #168 (after #125 and #167) so that `bash -c "$(curl ...)"` is used, but the web page seems not to have reflected it yet.
