### ISSUE TITLE
battery_percentage: command not found

### ISSUE THREAD

**Issue by HishamYUM** [ohmybash/oh-my-bash#220]
I was in zsh, and after I changed my theme to "kitsune", and changed my shell to bash I got this error line "battery_percentage: command not found". But my shell is working properly anyway. How can I fix this?
I am using Kali Linux 2021.1

**Comment by atchisson** [comment]
Hi,

It looks like `kitsune` theme need the battery plugin.
To enable it, open the file $HOME/.bashrc, look for `plugins=(` and add `battery` is the list.

Hope it helped!

**Comment by akinomyoga** [comment]
Thanks for the report. I've checked the implementation of `battery.plugin.sh` to find that it actually uses functions `about` and `group`. In the past, there seems to have been a related issue #68 (#104) for the function `_command_exists`. These functions are defined in [`bash-it`](https://github.com/Bash-it/bash-it). I guess this file was originally the plugin designed for Bash-it and then just copied into oh-my-bash without adjustment. I think I need to refactor the implementation of `battery` later.

**Comment by akinomyoga** [comment]
I've fixed them in PR #289.
- The problem that `group` and `about` are not found is fixed in commit b2ba5d8.
- The problem that `battery` plugin is not loaded should be resolved by commit 509a8b3.
- There are other bug fixes in both `kitsune.theme` and `battery.plugin`.

@dokuur Could you test the branch `fix-kitsune-and-battery`?

**Comment by akinomyoga** [comment]
I have merged #289. Thanks.
