### ISSUE TITLE
Upgrade breaks if you have modified any part of oh my bash's folder

### ISSUE THREAD

**Issue by dchurch315** [ohmybash/oh-my-bash#299]
One of the first changes I do when using Oh my Bash is to shorten to prompt by editing the theme file, such as agnoster.theme.sh. suggested in the wiki. The side effect of this is since the upgrade process runs with git, this triggers an error and the upgrade halts until you handle the issue with the local origin.

Since you have several automated upgrade methods and actions that you allow for, you may wish to check for uncommitted file changes and move them to a temp location during upgrade. Then alert the user that they need to handle the merge of their customization afterwards. Alternatively it might be better to perform a move of a theme to an gitignore'd location when the theme is selected rather than working directly with the source in the themes folder. Then any upgrades to the theme master could either be merged with the current theme in use or prompt the user to use the previous theme as-is.

**Comment by akinomyoga** [comment]
Actually, the users who want to modify the existing themes are supposed to first copy the theme subdirectory in the directory [`custom/themes/`](https://github.com/ohmybash/oh-my-bash/tree/master/custom/themes) (the location can be configured by `$OSH_CUSTOM`) and to edit the copy instead of directly editing the original files managed by the version control. When `oh-my-bash.sh` finds the theme in the custom directory with the same name as the bundled one, it will use the version in the custom directory. In this way, users can control which variations of the theme the user uses. If one wants to keep track of the upstream changes and merge it occasionally either manually or by using git, the user is expected to perform the merging on their own.

The wiki page seems to be edited by some users, but I guess we should update it correctly. Also, we may include in README how to make changes without being annoyed by the upgrades.

**Comment by dchurch315** [comment]
Thank you for clarifying - you may want to even prompt the users with which files caused the upgrade error as part of the error message rather than just the git one. Feel free to close.

**Comment by akinomyoga** [comment]
Thank you for updating the wiki page! I think I'll later look at what would happen in automatic upgrading when there are conflicting changes and see there is any better way to detect to resolve the problem.

**Comment by akinomyoga** [comment]
I have checked what happens if we try to upgrade oh-my-bash when we have uncommited changes in the working tree. I got the following result:

```console
[Oh My Bash] Would you like to check for updates? [Y/n]: y
Updating Oh My Bash
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
There was an error updating. Try again later?
murase@chatoyancy:~/.../ohmybash/oh-my-bash+2$
```

I think this is fine. The error messages is also understandable.

Next, I have checked when we have new local commits that conflict with the upstream version. The result is as follows:


```console
murase@chatoyancy:~/.../ohmybash/oh-my-bash+2$
murase@chatoyancy:~/.../ohmybash/oh-my-bash+2$ upgrade_oh_my_bash
Updating Oh My Bash
From github.com:ohmybash/oh-my-bash
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
 lib/utils.sh     |  5 +----
 oh-my-bash.sh    | 15 +++++++++++++++
 tools/install.sh | 49 ++++++++++++++++++++++++++++++++++++++++---------
 3 files changed, 56 insertions(+), 13 deletions(-)
Auto-merging lib/utils.sh
CONFLICT (content): Merge conflict in lib/utils.sh
error: could not apply ab375ef... user changes conflicting with upstream
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply ab375ef... user changes conflicting with upstream
There was an error updating. Try again later?
murase@chatoyancy:~/.../ohmybash/oh-my-bash+2$
```

The index becomes some intermediate state for rebasing, and the working tree is rewritten for conflict resolution. This causes problems when the user try to source the conflicting files. We need to run `git rebase --abort` to recover the original state.


In commit e58334b, now `git rebase --abort` is automatically run on the upgrading failure, and proper instructions about how to correctly upgrade oh-my-bash are printed. Also, I have added descriptions on how to modify a theme without being bothered by the upgrading conflicts (e58334b, cc50c22).
