### ISSUE TITLE
Upgrade is broken on Centos 7

### ISSUE THREAD

**Issue by flytbird** [ohmybash/oh-my-bash#311]
Hi, 

Since commit 463b9c3 (tools/upgrade: Return to the original working directory after upgrading) upgrade process is broken.
The reason is on Centos 7 git version (1.8.3.1) doesn't have "-C" option.

Regards,

**Comment by akinomyoga** [comment]
Thank you for the report! I have pushed a fix 9909fff to `master`. The option `-C` seems to have been only supported from 1.8.5 (https://github.com/git/git/commit/44e1e4d67d5148c245db362cc48c3cc6c2ec82ca). On the other hand, the options `--git-dir` and `--work-tree` seems to have ben supported since 1.5.3 (https://github.com/git/git/commit/892c41b98ae2e6baf3aa13901cb10db9ac67d2f3). I switched to use `--git-dir` and `--work-tree`.
