### ISSUE TITLE
Auto completion with multi-line file name

### ISSUE THREAD

**Issue by PMExtra** [ohmybash/oh-my-bash#341]
```sh
touch 'multi-'$'\n''line'

echo > 'multi-
line-
2'
```

These commands can create files with break-line character.

```plain
# ls
'multi-'$'\n''line'  'multi-'$'\n''line-'$'\n''2'
```

Then if I use `tab` key to auto complete file name:

```
# rm multi{tab}
2       line    line-   multi-  
```

It's so weird, oh-my-bash assumes the new line is a separator with another file.

Reference:
https://stackoverflow.com/a/23357277/6401252

**Comment by akinomyoga** [comment]
Oh My Bash (OMB) itself doesn't provide the completion for `rm`, but instead [bash-completion](https://github.com/scop/bash-completion) (which is [automatically loaded by OMB](https://github.com/ohmybash/oh-my-bash/blob/1272a398005c9f6c43e1567078a708fd500624d2/lib/bourne-shell.sh#L101-L105) if the system has it) provides it. Then, this problem is already reported at https://github.com/scop/bash-completion/issues/704. However, it is difficult to re-implement the entire `bash-completion` so that it handles newlines properly. As I have written there, this is due to the design of Bash itself whose builtin command `compgen` produces the completions separated by newlines. It is difficult to solve the problem unless Bash supports the NUL-separated output of `compgen` (for example with a certain option).

**Comment by PMExtra** [comment]
@akinomyoga Thanks for your patience.

**Comment by akinomyoga** [comment]
I'm actually thinking of sending a patch for a new option `-z` or `-0` of `compgen` to Bash. If you are interested, this is the current patch for the devel branch of Bash:

[bash-devel-add-compgen-zflag.zip](https://github.com/ohmybash/oh-my-bash/files/8996527/bash-devel-add-compgen-zflag.zip)

The development of Bash has a kind of *lifecycle*, and it is currently in *the maintenance stage* so would not accept new features. I guess it will get in *the development stage* about a half year later so am thinking of submitting the patch at that time.

Thank you anyway for reporting the issue!
