### ISSUE TITLE
powerline theme runs sudo by default

### ISSUE THREAD

**Issue by jsharpe** [ohmybash/oh-my-bash#38]
On some shared systems running sudo would result in an automatic ban of an account. Running sudo should be an opt in process by default rather than opt out.

**Comment by Kreyren** [comment]
Better way to handle root elevation was submitted in https://github.com/ohmybash/oh-my-bash/pull/75

**Comment by Kreyren** [comment]
Assigned P1 since this is security issue.

**Comment by akinomyoga** [comment]
> Assigned P1 since this is security issue.

This doesn't have any actual security risk though it may cause troubles by false-positive detection of `sudo` abuses.

I've just made the sudo check opt-in 1d1b160. This should be the sufficient and correct fix. @jsharpe Thank you for the suggestion!

I also updated the check to use `cat` instead of relying on non-POSIX `uptime`8c6b66c.
