### ISSUE TITLE
CD + Tab unnecessary results in home directory

### ISSUE THREAD

**Issue by AndyOkami** [ohmybash/oh-my-bash#448]
Environment: WSL2 Debian
Hey, I would like for cd+space+tab to show the files and folders in home directory, when used inside home directory. Instead I get the following:
![image](https://github.com/ohmybash/oh-my-bash/assets/31320092/1141f605-39e6-49bf-a185-c911a1bc90d1)
How can I get the cd to work as it used to in normal bash? Where should I look and what should I change?

**Comment by jikerdev** [comment]
> Ok, I figured it out. Aparently a setting enabled "complete -A cd" in bashrc. By adding "complete -d cd" in bashrc, the issue was fixed

can you give a configuration sample ?

**Comment by CouldBeThis** [comment]
I had this problem to. 

Eventually I figured out that adding 

```sh
complete -d cd
```

to the `.bashrc` only works if it goes *after*

```sh
source /home/un/.config/broot/launcher/bash/br
```

which is for [`broot`](https://github.com/Canop/broot). I don't know why these two applications are interacting this way or if it would happen in other situation. The easiest advice might be to put the line at the very end of `.bashrc`.

**Comment by PinkD** [comment]
> Ok, I figured it out. Aparently a setting enabled "complete -A cd" in bashrc. By adding "complete -d cd" in bashrc, the issue was fixed

I don't have `complete -A cd` in my `.bashrc`, but I still have this problem. Adding `complete -d cd` solves the problem. But I'm still wondering what causes this. Does omb change the default complete settings for all command?

**Comment by phyuany** [comment]
***@***.***

**Comment by akinomyoga** [comment]
This happens when `bash-completion` is loaded and `shopt -s cdable_vars` is set. This is intentional behavior by `bash-completion` because when `shopt -s cdable_vars` is set, variable names can also be specified to the `cd` builtin.

- Oh-My-Bash (OMB) sets `shopt -s cdable_vars`.
- OMB doesn't define any completion settings for `cd`, but OMB loads `bash-completion` automatically when OMB finds it in the system, and `bash-completion` defines a completion for `cd` to generate variable names when `shopt -s cdable_vars`.
- OMB also defines many shell variables.

As a consequence of these setups, when OMB is loaded and `bash-completion` exists in the system, the completion for the `cd` builtin produces many variable names.
