### ISSUE TITLE
Terminal has missing symbol why iTerm does not

### ISSUE THREAD

**Issue by curiouslaw** [ohmybash/oh-my-bash#511]
**OS:** MacOS Ventura 13.6.3

I just noticed this weirdness, there is an unknown symbol in Terminal, while it doesn't occur in iTerm. It occurs of the solid right/left pointing triangle. Here is the screenshot.

![Screenshot 2023-12-25 at 9 54 53 PM](https://github.com/ohmybash/oh-my-bash/assets/17136244/a29c62cc-2c79-40fb-942b-f06a45000fa4)

Let me know if you need more information.

**Comment by akinomyoga** [comment]
This is because some themes in Oh My Bash require the terminal's support for the Powerline fonts. iTerm2 has built-in support for rendering Powerline glyphs, which is special to iTerm2. For other typical terminals including iTerm2, you need to install any powerline font and configure it for the terminal. The way to install and configure the powerline fonts is described in the following Q&A:

- [iterm - Does Terminal.app has Powerline glyph support? - Ask Different](https://apple.stackexchange.com/a/451768/437969)

**Comment by curiouslaw** [comment]
Ahh yes you're right, thanks for the explanation and solution @akinomyoga!
