### ISSUE TITLE
Completion broken when sourcing file

### ISSUE THREAD

**Issue by RoggeHaj** [ohmybash/oh-my-bash#547]
In Bash, at least on version 4.4.20(1)-release (Ubuntu 18.04), I get an error when trying to source a file with completion. I've tried with a clean install  of Oh My Bash, just to rule out any custom modifications, with the same results.

### Steps to reproduce

1. Enter leading dot followed by a space character
2. Press `<TAB>`

### Expected behavior

Completion on file names and directories in current directory.

### Actual behavior

```bash
user1@computer1:~$ . bash: .: syntax error: operand expected (error token is ".")
```

### OSH version

`6c1bde9779841b096a88e96f43fda210b78e5ddc`

**Comment by akinomyoga** [comment]
Thanks for the report. What are the results of the following commands (after attempting the completion for the command `.`)?

```bash
$ . [TAB] # <-- attempt the completion for the command . to intentionally produce error
$ complete -p .
$ declare -p BASH_COMPLETION_VERSINFO
```

**Comment by RoggeHaj** [comment]
```bash
$ complete -p .
bash: complete: .: no completion specification
$ declare -p BASH_COMPLETION_VERSINFO
declare -a BASH_COMPLETION_VERSINFO=([0]="2" [1]="8")
```

**Comment by akinomyoga** [comment]
Does the problem reproduce after running `unalias -a`?

```bash
$ unalias -a
$ . [TAB] <--- attempt completion
```

**Comment by RoggeHaj** [comment]
Yes, same as before

```bash
$ unalias -a
$ . bash: .: syntax error: operand expected (error token is ".")
```

**Comment by akinomyoga** [comment]
Thank you. Hmm, what is the result of the following command?

```bash
$ complete -p -D
```

**Comment by RoggeHaj** [comment]
```bash
$ complete -p -D
complete -F _completion_loader -D
```

**Comment by akinomyoga** [comment]
I now tried OMB + bash-completion-2.8 + bash-4.4, but the problem doesn't seem to arise. I'd like to get a debug trace. Could you run the following commands?

```bash
$ exec 3> debug.txt; BASH_XTRACEFD=3; set -x
$ . [TAB] <-- attempt completion
$ set +x
```

Then, a file `debug.txt` is created. Could you attach the file in reply? You can drag and drop the file into the textarea to attach a file in GitHub.

**Comment by RoggeHaj** [comment]
[debug.txt](https://github.com/ohmybash/oh-my-bash/files/14839074/debug.txt)

**Comment by akinomyoga** [comment]
Thank you. I've checked its content. I think `_xspecs` is an indexed array in your environment (instead of an associated array) for some reason. What are printed on the session start when you put the line `declare -p _xspecs >&2` around the line `source "$OSH"/oh-my-bash.sh` in your `~/.bashrc`? More specifically, what are output on the session start when you add the following changes to `~/.bashrc`?

```diff
diff --git a/templates/bashrc.osh-template b/templates/bashrc.osh-template
index 4f1851d..c9ffac0 100644
--- a/bashrc
+++ b/bashrc
@@ -113,7 +113,9 @@ plugins=(
 #      plugins+=(tmux-autoattach)
 #  fi

+declare -p _xspecs >&2
 source "$OSH"/oh-my-bash.sh
+declare -p _xspecs >&2

 # User configuration
 # export MANPATH="/usr/local/man:$MANPATH"
```

**Comment by akinomyoga** [comment]
OK, I could reproduce the problem. The problem arises when bash-completion-2.8 is loaded inside OMB. This happens because OMB sources modules inside a shell function, while `bash-completion-2.8` declares the associative array `_xspecs` as `declare -A _xspecs`. When `declare -A _xspecs` is executed inside `source` called from a function, it creates a local variable `_xspecs`, which disappears after the initialization. This causes the problem.

There is also a report at https://github.com/scop/bash-completion/issues/360. The fix to `bash-completion` was given by https://github.com/scop/bash-completion/pull/210 and included in the release 2.9.

**Comment by akinomyoga** [comment]
A workaround for bash-completion-2.8 is to source bash-completion at the top level of `~/.bashrc`:

```diff
diff --git a/templates/bashrc.osh-template b/templates/bashrc.osh-template
index 4f1851d..40e85c2 100644
--- a/templates/bashrc.osh-template
+++ b/templates/bashrc.osh-template
@@ -4,6 +4,8 @@ case $- in
     *) return;;
 esac

+source /usr/share/bash-completion/bash_completion
+
 # Path to your oh-my-bash installation.
 export OSH=~/.oh-my-bash

```

**Comment by RoggeHaj** [comment]
Works like a charm. Many thanks!
