### ISSUE TITLE
No venv for "brainy" theme

### ISSUE THREAD

**Issue by naiaraAM** [ohmybash/oh-my-bash#579]
Hi. I just look at all possible solutions but I couldn't find any. venv promt doesn't appear when I use brainy theme even though I have set to true the var in `~/.bashrc`. Any ideas?

**Comment by akinomyoga** [comment]
That is just because the `brainy` theme doesn't support the python venv information. You can define your own segment by the shell function such as `__brainy_prompt_venv` and put `venv` in [`___BRAINY_{TOP_LEFT,TOP_RIGHT,BOTTOM}`](https://github.com/ohmybash/oh-my-bash/blob/master/themes/brainy/README.md#prompt-segments-order), or you can modify the existing segment `__brainy_prompt_python` to generate the virtual environment information instead of Python version.

**Comment by akinomyoga** [comment]
I think I can adjust the existing segment `__brainy_prompt_python` to include `venv` and `condaenv` as well as the currently supported Python version.

**Comment by akinomyoga** [comment]
I updated the `brainy` theme in the `master` branch. Could you update Oh My Bash by running `upgrade_oh_my_bash` and check the behavior?

**Comment by naiaraAM** [comment]
Uhm, seems to not be working for me, using conda env btw.
![image](https://github.com/ohmybash/oh-my-bash/assets/100145013/e8ab9300-1a9d-43f1-a8ba-8c0731918a0b)

**Comment by akinomyoga** [comment]
Ah, sorry. I forgot to explain that in the `brainy` theme, one needs to enable the prompt segment by using [`brainy show python`](https://github.com/ohmybash/oh-my-bash/blob/master/themes/brainy/README.md#on-the-fly-using-brainy-command).

```bash
# .bashrc

# Put this somewhere after source oh-my-bash.sh
brainy show python
```

Or you may put the following line instead:

```bash
# .bashrc

# Put this somewhere after source oh-my-bash.sh
THEME_SHOW_PYTHON=true
```

**Comment by naiaraAM** [comment]
Perfect now, showing type of virtual env (conda, python, whatever), name of venv and python version of venv.
