### ISSUE TITLE
Set HISTSIZE and HISTFILESIZE to -1

### ISSUE THREAD

**Issue by Charadon** [ohmybash/oh-my-bash#586]
According to the official bash manual:
>Numeric values less than zero result in every command being saved on the history list (there is no limit).

This means the correct way is to set it to a negative number. This also fixes an issue where it crashes `mksh` due to HISTSIZE having a "bad number" (As it has no number).

**Comment by akinomyoga** [comment]
There is a non-trivial story.

Oh My Bash (OMB) intends to offer support to Bash >= 3.2 (it should be noted that macOS by default ships with Bash 3.2). However, `HISTSIZE=-1` and `HISTFILESIZE=-1` are only supported in Bash >= 4.3. If we set `HISTSIZE=-1` and `HISTFILESIZE=-1` in Bash < 4.2, the history stops working; the history becomes always empty, and also the content of the history file would be lost. Instead, although it's not documented, the history becomes unlimited also when `HISTSIZE` and `HISTFILESIZE` are set to the empty string. This works with all the supported Bash versions, and this is the current strategy of OMB.

For the `mksh` error, one possible option is not to export `HISTSIZE` and `HISTFILESIZE`. They are just shell variables that control the behavior of the current Bash process, so in principle, they do not need to be environment variables. However, there is also non-trivial background of exporting these variables. When the initialization of Bash becomes incomplete due to an error in `~/.bashrc`, the variables `HISTSIZE` and `HISTFILESIZE` can be left in the uninitialized state, and then it can truncate the user's history file. To avoid the possible loss of the user's history by child Bash processes with a possible `~/.bashrc` failure, `HISTFILE` and `HISTFILESIZE` are intentionally exported so that it would have the desired value even if the initialization fails in the middle.

Another option is to initialize `HISTSIZE=-1` and `HISTFILESIZE=-1` only when the current Bash version is 4.3 or above or, otherwise, initialize `HISTSIZE=` and `HISTFILESIZE=`. But then, the problem still arises with Bash < 4.3, and also `HISTSIZE=-1` and `HISTFILESIZE=-1` may truncate the user's history file when a different version Bash reads it through the environment variables.

**Comment by Charadon** [comment]
On MacOS:
While it is unfortunate that Mac only includes 3.2 out of the box. A few things should be noted:
1. Anyone who uses oh-my-bash is also probably using a 3rd party package manager such as Homebrew, Macports, or pkgsrc. All of which include the a much newer, if not the latest, version of bash:
- https://pkgsrc.se/shells/bash
- https://formulae.brew.sh/formula/bash
- https://ports.macports.org/port/bash/
2. As far as I know, Mac is the *only* OS that is still supported that includes 3.2, a version from 2006. I believe it wouldn't be unreasonable to tell users "Hey, use that package manager you definitely already have to install newer bash."
---

Now, if we want to keep 3.2 support, you can probably pretty easily just use a one-liner to grab the version number, like this:
`bash --version | awk 'NR==1{print $4}'`
and do a simple `if` check to see what behavior you should do:
```
if [[ ! "$(bash --version | awk 'NR==1{print $4}')" =~ 3.2.* ]];
then
        export HISTSIZE=-1
        export HISTFILESIZE=-1
else
        export HISTSIZE=
        export HISTFILESIZE=
fi
```

Again, I think just dropping 3.2 support, and telling Mac users to *not* use a bash version from 20 years ago is the better option, but if you want to keep support, that if statement is the easiest way.

**Comment by akinomyoga** [comment]
Bash 3.2 in macOS is just an example. I wrote that `-1` is only supported in Bash 4.3 in my previous reply. There are Bash 4.0, 4.1, and 4.2 between 3.2 and 4.3. Ubuntu 16.04 LTS with Bash 4.2 is still in the market.

I already mentioned the switching of `HISTSIZE=-1` and `HISTSIZE=` in my previous reply, where I noted that such a setting deletes the user's history file when a lower version of Bash exists in the system and is started by chance.

Also, `bash --version` is not the correct way to get the version of the current Bash. `bash --version` picks the version of Bash found in the current value of `PATH`. When there are multiple versions of Bash in the system, it's not trustable. The correct way is to use the shell variable `BASH_VERSINFO`.

**Comment by Charadon** [comment]
> Bash 3.2 in macOS is just an example. I wrote that -1 is only supported in Bash 4.3 in my previous reply. There are Bash 4.0, 4.1, and 4.2 between 3.2 and 4.3. Ubuntu 16.04 LTS with Bash 4.2 is still in the market.

Right, I forgot ubuntu expanded their support to 10 years.

> Also, bash --version is not the correct way to get the version of the current Bash. bash --version picks the version of Bash found in the current value of PATH. When there are multiple versions of Bash in the system, it's not trustable. The correct way is to use the shell variable BASH_VERSINFO.

And that's why you don't write shell code when you're tired and have been working with Korn Shell for the past week 😓
---

Well, I suppose I can always just warn users if they run into the problem down the line with the program i'm making if they happen to use oh-my-bash like I am. Or if I could get in contact with the blasted mksh devs haha

But at the very least, if someone has this issue, it's documented now!

**Comment by akinomyoga** [comment]
I was thinking about different solutions.

Another solution is to prepare a shell function `mksh`, where we unset `HISTSIZE` and call the executable `mksh`. i.e., `function mksh { (unset -v HISTSIZE; exec mksh "$@"); }`. However, this still has the problem that I mentioned for the solution of not making `HISTSIZE` and `HISTFILESIZE` environment variables. When a Bash process is started from `mksh`, it may truncate the user's history file to 500 when bashrc is not loaded.

Another solution is to keep `HISTFILESIZE` empty but to switch `HISTSIZE` between an empty string and `-1` depending on the current Bash version (`obtained from BASH_VERSINFO`). This way, we can avoid clearing the user's history file even when a lower version of Bash is started without configuration.

Another solution is to specify an extremely large number to `HISTSIZE` and `HISTFILESIZE` explicitly. This is technically not the *unlimited* history, but it should effectively work as far as we set an extremely large number that is unlikely to be reached. Some users (without knowing the feature of `HISTSIZE=` or `HISTSIZE=-1`) set explicit values like `10000` or `100000`, but these values are actually not unreachable values. The number of commands of heavy users may reach one million, We may set `HISTSIZE=99999999` or `((HISTSIZE=0x7FFFFFFF))`. This is still a *finite* number, but the integer might overflow if we go further.

**Comment by Charadon** [comment]
> Another solution is to specify an extremely large number to HISTSIZE and HISTFILESIZE explicitly. This is technically not the unlimited history, but it should effectively work as far as we set an extremely large number that is unlikely to be reached. Some users (without knowing the feature of HISTSIZE= or HISTSIZE=-1) set explicit values like 10000 or 100000, but these values are actually not unreachable values. The number of commands of heavy users may reach one million, We may set HISTSIZE=99999999 or ((HISTSIZE=0x7FFFFFFF)). This is still a finite number, but the integer might overflow if we go further.

Looking at the source code of Bash, bash assigns the variable in a C function called `sv_histsize` which stores the value of HISTSIZE in `int hmax`. According to the C standard, int is guaranteed to be *at least* 16-bit. Though, obviously in practice, most compilers make it 32-bit.

However, it appears to me that bash checks if the int width is 4, thus checking if it's 32-bit at least. 

I can't confidentaly confirm that, however because m4 is an arcane language made by demons.

So, if you wanted to be super safe, that means HISTSIZE can only 32767 max. But in practice i'd say 2147483647 would be the best value.

**Comment by akinomyoga** [comment]
I added d12ee76. I used `0x7FFF7FFF` so that it becomes `0x7FFF` when truncated to 16 bits.
