### ISSUE TITLE
oh-my-bash terminal weirdness

### ISSUE THREAD

**Issue by sw030453** [ohmybash/oh-my-bash#610]
I'm having a couple of terminal problems using _oh-my-bash_ (macOS **_Terminal_**; **TERM** set to _xterm-256color_)...

-  When I'm typing a particularly long command,  when ever I type to about the 78th character or so, the text wraps around to the beginning of the same line and starts overwriting the prompt (see **Shot1.png**).

- Sometimes when I do a command-line editing operation (say _ctrl-p_) the current line is duplicated above the current line and the cursor motion takes place on the duplicated line (I tried to capture this in a screen shot but couldn't).

Neither of these things happen with a vanilla `bash` and no _oh-my-bash_ (see **Shot3.png**).  It happens on local as well as remote (_ssh_) sessions to systems where I have the same _oh-my-bash_ setup installed.

My shell options are in **shopt.txt**.  The code for my custom theme (a variation of vscode) is in **stevewi.theme.sh.txt**).

There's probably a control character I need to add to my theme prompt...  Anyone run across this before?  What did you do to fix it?

Thanks in advance...

<img width="892" alt="Shot1" src="https://github.com/user-attachments/assets/b0bfe1bc-5383-4b09-b4ac-40ad372869d3">

<img width="890" alt="Shot3" src="https://github.com/user-attachments/assets/ba8d8728-0010-4253-aa56-98d294d3c00a">

[shopt.txt](https://github.com/user-attachments/files/16936563/shopt.txt)

[stevewi.theme.sh.txt](https://github.com/user-attachments/files/16936566/stevewi.theme.sh.txt)

**Comment by akinomyoga** [comment]
This is just because `${bold}`, `${green}`, `${blue}`, `${plain}`, and `${red}` in your `gitbranch` variable do not see the local variables. The value of `gitbranch` is quoted by `'...'`, so it's not expanded inside the function. It is expanded when Bash evaluates `PS1`, which is outside the function, so it doesn't see the local variables that you prepared. Instead they pick *the values of the global variables of the same names*, which are not necessarily enclosed within `\[` and `\]`.

**Comment by sw030453** [comment]
That fixed it.  Thanks  for your help!
